language: generic
services:
  - docker

before_install:
  - docker build -t dracot/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dracot/react-test npm test

after_success:
  - docker build -t dracot/multi-client ./client
  - docker build -t dracot/multi-nginx ./nginx
  - docker build -t dracot/multi-server ./server
  - docker build -t dracot/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push dracot/multi-client
  - docker push dracot/multi-nginx
  - docker push dracot/multi-server
  - docker push dracot/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket: elasticbeanstalk-us-east-2-794664116661
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
